const MAX_LOGGED_DEVICES = Number(process.env.MAX_LOGIN_ALLOWED) || 3

const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET || ''
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET || ''
const IS_PRODUCTION = process.env.NODE_ENV === 'production'

const ACCESS_TOKEN_EXPIRES_IN = process.env.ACCESS_TOKEN_EXPIRES_IN || '60s'
const REFRESH_TOKEN_EXPIRES_IN =
  process.env.REFRESH_TOKEN_EXPIRES_IN || '86400s'
const region = process.env.Region || 'UTC'

export {
  MAX_LOGGED_DEVICES,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  IS_PRODUCTION,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  region,
}
